version: '3'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}

    volumes:
      - ./database/user.sql:/docker-entrypoint-initdb.d/user.sql

    ports:
      - "3312:3306"

    networks:
      - spring-cloud-microservices

  authentication-service:
    build:
      context: .
      dockerfile: ./server/Authentication/Dockerfile-dev
    container_name: authentication-service-container

    restart: always

    depends_on:
      - mysql-db
    
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - PORT=${AUTHENTICATION_SERVICE_PORT}

    links:
      - mysql-db:mysql
    expose:
      - ${AUTHENTICATION_SERVICE_PORT}
    ports:
      - ${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}
    networks:
      - spring-cloud-microservices
    
  common-data-service:
    build:
      context: .
      dockerfile: ./server/commonService/Dockerfile-dev
    container_name: common-data-service
    restart: always
    depends_on:
      - mysql-db
      - redis-cache

    
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - PORT=${COMMON_SERVICE_PORT}
      

    links:
      - mysql-db:mysql
    expose:
      - ${COMMON_SERVICE_PORT}
    ports:
      - ${COMMON_SERVICE_PORT}:${COMMON_SERVICE_PORT}
    networks:
      - spring-cloud-microservices
        
  react-ui:
    build:
      context: .
      dockerfile: ./client/DockerFile
    container_name: react-service-container
    stdin_open: true
    restart: always
    expose:
      - ${REACT_APP_PORT}
    
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}

    environment:
      - REACT_APP_COMMON_DATA_SERVICE_PORT = ${COMMON_SERVICE_PORT}
      - REACT_APP_AUTHENTICATION_SERVICE_PORT = ${AUTHENTICATION_SERVICE_PORT}
    
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    
    depends_on:
      - mysql-db
    networks:
      - spring-cloud-microservices
        

networks:
  spring-cloud-microservices:
    external: true